export type TInstanceRateLimitConfigurationKeys =
  | "RATE_LIMIT_API_KEY"
  | "RATE_LIMIT_SERVICE_TOKEN"
  | "RATE_LIMIT_AUTHENTICATION"
  | "RATE_LIMIT_EMAIL_VERIFICATION"
  | "RATE_LIMIT_ASSET"
  | "RATE_LIMIT_ANONYMOUS";
